### ISSUE TITLE
Performance of the pretrained V-Net

### ISSUE THREAD

**Issue by nguyenpbui** [koncle/CoraNet#6]
Dear authors,
Firstly, thank you for your amazing work.
To reproduce your results, I used your pretrained V-Net to train semi-supervised segmentation. I first tested your pretrained V-Net on Pancreas dataset (I pre-processed this dataset before testing by your code) but the results are very different. Specifically, it achieved 0.1801 Dice, 0.1062 Jaccard, 50.0687 ASD, and 24.28 95HD while your results in the paper are 0.6996 Dice, 0.5555 Jaccard, 1.64 ASD, and 14.27 95HD.
Can you explain about it or update your repository with testing file ???

**Comment by koncle** [comment]
The pretrained model was trained with our method instead of the baseline. I tested the model and it achieved 0.79 Dice. Then I re-preprocessed the pancreas dataset to do the test and got the same result. The test file is  `test_util.py` and is the same as the current repository. The result you got may be caused by the preprocess procedure.  Did you preprocess the dataset in the right way? I uploaded the [preprocessed dataset](https://drive.google.com/file/d/1AvpmXJU8ecHe4PGrP2Lwqvq-4OyRmPpZ/view?usp=sharing) and you can download it and test again.

**Comment by nguyenpbui** [comment]
Thank you for your reply. I pre-processed this dataset before testing by your code. In your attached link, your preprocessed dataset only has 75 MRI scans while the actual number is 82. Can you share with me your preprocessed dataset?
Thank you very much

**Comment by UESTC-Med424-JYX** [comment]
> The pretrained model was trained with our method instead of the baseline. I tested the model and it achieved 0.79 Dice. Then I re-preprocessed the pancreas dataset to do the test and got the same result. The test file is `test_util.py` and is the same as the current repository. The result you got may be caused by the preprocess procedure. Did you preprocess the dataset in the right way? I uploaded the [preprocessed dataset](https://drive.google.com/file/d/1AvpmXJU8ecHe4PGrP2Lwqvq-4OyRmPpZ/view?usp=sharing) and you can download it and test again.

Can you please upload the preprocessed data set again? The current file is invalid. The questioner and I encountered the same problem.
