### ISSUE TITLE
Confused about the size of testing set.

### ISSUE THREAD

**Issue by byhwhite** [koncle/CoraNet#9]
Dear author:
I have been studying on your work for a while. I noticed that in pancreas_preprocess.py you crop all image according to label and saved them. So testing on foreground areas only. I'm confused whether it should testing on the whole image, using sliding window method.
Looking forward to your reply!

**Comment by koncle** [comment]
Thank you for your attention. In fact, testing on the whole image is more reasonable since it matches the real situation. However, to compare to previous works (e.g., UA-MT, DTC), we follow the code from [DTC](https://github.com/HiLab-git/DTC/blob/master/code/test_LA.py#L45) that first preprocesses the data and then tests with these preprocessed data.

**Comment by byhwhite** [comment]
Thanks for your reply! It helps a lot!
